import one from "../../assets/images/article.jpg";
const Research_articles_data = [
    {
        link: "/research-articles-detail",
        head: "Lorem ipsum dolor sit amit lorem ipsum dolor sit amit 1",
        img: one,
        date: "January 30, 2021",
        time: "4:00 AM",
        course: "Course 1",
        name: "Name 1",
    },
    {
        link: "/research-articles-detail",
        head: "Lorem ipsum dolor sit amit lorem ipsum dolor sit amit 2",
        img: one,
        date: "March 3, 2021",
        time: "2:30 PM",
        course: "Course 2",
        name: "Name 2",
    },
    {
        link: "/research-articles-detail",
        head: "Lorem ipsum dolor sit amit lorem ipsum dolor sit amit 3",
        img: one,
        date: "June 3, 2021",
        time: "6:30 PM",
        course: "Course 3",
        name: "Name 3",
    },
    {
        link: "/research-articles-detail",
        head: "Lorem ipsum dolor sit amit lorem ipsum dolor sit amit 4",
        img: one,
        date: "September 13, 2021",
        time: "11:30 AM",
        course: "Course 4",
        name: "Name 4",
    },
    {
        link: "/research-articles-detail",
        head: "Lorem ipsum dolor sit amit lorem ipsum dolor sit amit 5",
        img: one,
        date: "December 15, 2021",
        time: "11:00 AM",
        course: "Course 5",
        name: "Name 5",
    },
    {
        link: "/research-articles-detail",
        head: "Lorem ipsum dolor sit amit lorem ipsum dolor sit amit 6",
        img: one,
        date: "January 19, 2022",
        time: "5:59 AM",
        course: "Course 6",
        name: "Name 6",
    },
]
export default Research_articles_data;